name: Arafat Kazi
favicon: null
layout_spectrum: 0.0852231988683343
typography_spectrum: 0.7460327765438706
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9932951794471592
  lightness: 0.15420825500041246
  saturation: 0.5952417817898095
  rhythmicContrast: 0.04117739270441234
purpose: []
